2019-02-13 21:33:41,855 - invest - ERROR - this is error  - [logger.py:33]
2019-02-13 21:33:41,893 - LoginTest - INFO - 开始执行第1用例 - [test_login.py:35]
2019-02-13 21:33:42,016 - LoginTest - ERROR - 第1用例执行结果：FAIL - [test_login.py:46]
2019-02-13 21:33:42,021 - LoginTest - INFO - 开始执行第2用例 - [test_login.py:35]
2019-02-13 21:33:42,118 - LoginTest - ERROR - 第2用例执行结果：FAIL - [test_login.py:46]
2019-02-13 21:33:42,122 - LoginTest - INFO - 开始执行第3用例 - [test_login.py:35]
2019-02-13 21:33:42,217 - LoginTest - ERROR - 第3用例执行结果：FAIL - [test_login.py:46]
2019-02-13 21:33:42,220 - LoginTest - INFO - 开始执行第4用例 - [test_login.py:35]
2019-02-13 21:33:42,309 - LoginTest - ERROR - 第4用例执行结果：FAIL - [test_login.py:46]
2019-02-14 01:03:08,414 - invest - ERROR - this is error  - [logger.py:37]
2019-02-14 01:03:15,134 - LoginTest - INFO - 开始执行第1用例 - [test_login.py:35]
2019-02-14 01:07:56,514 - invest - ERROR - this is error  - [logger.py:37]
2019-02-14 01:07:56,543 - LoginTest - INFO - 开始执行第1用例 - [test_login.py:35]
2019-02-14 01:07:56,659 - LoginTest - INFO - 开始执行第2用例 - [test_login.py:35]
2019-02-14 01:07:56,721 - LoginTest - INFO - 开始执行第3用例 - [test_login.py:35]
2019-02-14 01:07:56,778 - LoginTest - INFO - 开始执行第4用例 - [test_login.py:35]
2019-02-14 01:08:33,016 - invest - ERROR - this is error  - [logger.py:37]
2019-02-14 01:08:33,110 - LoginTest - INFO - 开始执行第1用例 - [test_login.py:35]
2019-02-14 01:09:16,122 - invest - ERROR - this is error  - [logger.py:37]
2019-02-14 01:09:16,169 - LoginTest - INFO - 开始执行第1用例 - [test_login.py:35]
2019-02-14 01:09:16,278 - LoginTest - INFO - 第1用例执行结果：PASS - [test_login.py:43]
2019-02-14 01:09:16,278 - LoginTest - INFO - 开始执行第2用例 - [test_login.py:35]
2019-02-14 01:09:16,369 - LoginTest - INFO - 第2用例执行结果：PASS - [test_login.py:43]
2019-02-14 01:09:16,369 - LoginTest - INFO - 开始执行第3用例 - [test_login.py:35]
2019-02-14 01:09:16,422 - LoginTest - INFO - 第3用例执行结果：PASS - [test_login.py:43]
2019-02-14 01:09:16,422 - LoginTest - INFO - 开始执行第4用例 - [test_login.py:35]
2019-02-14 01:09:16,485 - LoginTest - INFO - 第4用例执行结果：PASS - [test_login.py:43]
2019-02-14 01:22:58,558 - invest - ERROR - this is error  - [logger.py:37]
2019-02-14 01:23:11,345 - LoginTest - INFO - 开始执行第1用例 - [test_login.py:35]
2019-02-14 01:23:11,445 - LoginTest - INFO - 第1用例执行结果：PASS - [test_login.py:43]
2019-02-14 01:23:11,445 - LoginTest - INFO - 开始执行第2用例 - [test_login.py:35]
2019-02-14 01:23:11,498 - LoginTest - INFO - 第2用例执行结果：PASS - [test_login.py:43]
2019-02-14 01:23:11,498 - LoginTest - INFO - 开始执行第3用例 - [test_login.py:35]
2019-02-14 01:23:11,561 - LoginTest - INFO - 第3用例执行结果：PASS - [test_login.py:43]
2019-02-14 01:23:11,561 - LoginTest - INFO - 开始执行第4用例 - [test_login.py:35]
2019-02-14 01:23:11,630 - LoginTest - INFO - 第4用例执行结果：PASS - [test_login.py:43]
